### ISSUE TITLE
Error on the linear attention

### ISSUE THREAD

**Issue by John-Ge** [fla-org/flash-bidirectional-linear-attention#3]
I use the linear attention in the file of [linear attention](https://github.com/fla-org/flash-linear-attention/blob/main/fla/ops/simple_gla/chunk.py).
My code is:
```python
if __name__ == "__main__":
    q, k, v = (
        torch.randn(1, 1, 32, 64).cuda().to(torch.bfloat16),
        torch.randn(1, 1, 32, 64).cuda().to(torch.bfloat16),
        torch.randn(1, 1, 32, 64).cuda().to(torch.bfloat16),
    )
    # 调用 linear_attention 函数
    output = linear_attention(q, k, v)

    # 检查输出形状是否正确
    print("Output shape:", output.shape)  # 应为 (B, H, L, V)
```

I meet the following bug:
```bash
    raise CompilationError(fn.src, node, repr(e)) from e
triton.compiler.errors.CompilationError: at 46:33:    )
    KM_block_ptr = KM + off_bs_head * stride_km_bh + tl.arange(0, BK)

    o = tl.zeros([BL, BV], dtype=tl.float32)
    z = tl.zeros([BL], dtype=tl.float32)

    for offset_k in range(0, DK, BK):
        q = tl.load(Q_block_ptr, boundary_check=(0, 1))
        s = tl.load(S_block_ptr, boundary_check=(0, 1))
        km = tl.load(KM_block_ptr, mask=((offset_k + tl.arange(0, BK)) < DK))

        z += tl.sum(q * km[None, :], axis=1, keep_dims=False)
                                 ^
TypeError("sum() got an unexpected keyword argument 'keep_dims'")
```

Should we delete the [*keep_dims=False?* ](https://github.com/fla-org/flash-bidirectional-linear-attention/blob/f82852b4ca6e2ca2d1a6242f90fc3f9afbe3f44d/fbi_la/ops/linear_attn/attention.py#L236)
Thanks!

**Comment by hp-l33** [comment]
I think it might be an issue with the Triton version. Which version are you using? In my case, version 3.0.0 works well.

**Comment by John-Ge** [comment]
Thank you! My Triton version is 2.1.0, now it works after I update to 3.0.0.
